In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [59]:
player_data=pd.read_csv(r"C:\Users\vedan\Downloads\Player role classifier\data\australian football league\players.csv")

In [60]:
player_data.head()

,PlayerId,DisplayName,Height,Weight,Dob,Position,Origin
0,2020654979,"Aarts, Jake",177,75,8-Dec-94,Forward,Richmond
1,2018655703,"Abbott, Ryan",200,100,25-Jun-91,Ruck,Grovedale Tigers
2,2002652211,"Ablett, Gary",182,87,14-May-84,Forward,Geelong Falcons
3,2014651814,"Acres, Blake",191,90,7-Oct-95,Midfield,West Perth
4,2007653719,"Adams, Leigh",176,79,6-Apr-88,Forward,Eastern Ranges

In [61]:
player_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1725 entries, 0 to 1724
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PlayerId     1725 non-null   int64
 1   DisplayName  1725 non-null   object
 2   Height       1725 non-null   int64
 3   Weight       1725 non-null   int64
 4   Dob          1725 non-null   object
 5   Position     1725 non-null   object
 6   Origin       1721 non-null   object
dtypes: int64(3), object(4)
memory usage: 94.5+ KB

In [62]:
games_data= pd.read_csv(r"C:\Users\vedan\Downloads\Player role classifier\data\australian football league\games.csv")

In [63]:
games_data.head()

,GameId,Year,Round,Date,MaxTemp,MinTemp,Rainfall,Venue,StartTime,Attendance,...,HomeTeamScoreHT,HomeTeamScore3QT,HomeTeamScoreFT,HomeTeamScore,AwayTeam,AwayTeamScoreQT,AwayTeamScoreHT,AwayTeamScore3QT,AwayTeamScoreFT,AwayTeamScore
0,2012R0101,2012,R1,2012-03-24,24.0,12.2,0.0,Stadium Australia,7:20 PM,"38,203",...,3.3,3.4,5.70,37,Sydney,4.1,8.4,13.80,14.16,100
1,2012R0102,2012,R1,2012-03-29,25.7,9.7,0.0,M.C.G.,7:45 PM,"78,285",...,5.6,10.7,12.90,81,Carlton,3.2,8.7,11.13,18.17,125
2,2012R0103,2012,R1,2012-03-30,27.4,9.7,0.0,M.C.G.,7:50 PM,"78,466",...,10.6,14.1,20.17,137,Collingwood,2.7,7.9,12.16,16.19,115
3,2012R0104,2012,R1,2012-03-31,29.1,15.1,0.6,M.C.G.,1:45 PM,"33,473",...,7.4,8.8,11.12,78,Brisbane Lions,1.4,7.8,13.13,17.17,119
4,2012R0105,2012,R1,2012-03-31,28.2,19.7,0.0,Carrara,3:45 PM,"12,790",...,5.3,8.6,10.80,68,Adelaide,7.8,11.1,15.16,19.23,137

In [64]:
games_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2663 entries, 0 to 2662
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GameId            2663 non-null   object
 1   Year              2663 non-null   int64
 2   Round             2663 non-null   object
 3   Date              2663 non-null   object
 4   MaxTemp           2656 non-null   float64
 5   MinTemp           2656 non-null   float64
 6   Rainfall          2640 non-null   float64
 7   Venue             2663 non-null   object
 8   StartTime         2663 non-null   object
 9   Attendance        2663 non-null   object
 10  HomeTeam          2663 non-null   object
 11  HomeTeamScoreQT   2663 non-null   float64
 12  HomeTeamScoreHT   2663 non-null   float64
 13  HomeTeamScore3QT  2663 non-null   float64
 14  HomeTeamScoreFT   2663 non-null   float64
 15  HomeTeamScore     2663 non-null   int64
 16  AwayTeam          2663 non-null   object
 17  AwayTeamScoreQT   2663 non-null   float64
 18  AwayTeamScoreHT   2663 non-null   float64
 19  AwayTeamScore3QT  2663 non-null   float64
 20  AwayTeamScoreFT   2663 non-null   float64
 21  AwayTeamScore     2663 non-null   int64
dtypes: float64(11), int64(3), object(8)
memory usage: 457.8+ KB

In [65]:
stats_data=pd.read_csv(r"C:\Users\vedan\Downloads\Player role classifier\data\australian football league\stats.csv")

In [66]:
stats_data.head()

,GameId,Team,Year,Round,PlayerId,DisplayName,GameNumber,Disposals,Kicks,Marks,...,BrownlowVotes,ContestedPossessions,UncontestedPossessions,ContestedMarks,MarksInside50,OnePercenters,Bounces,GoalAssists,%Played,Subs
0,2012R0105,Adelaide,2012,R1,2011675768,"Callinan, Ian",4,18,14,5,...,0,9,9,0,3,0,0,0,84,-
1,2012R0105,Adelaide,2012,R1,2008681760,"Dangerfield, Patrick",65,25,13,3,...,0,14,11,0,1,1,1,0,92,-
2,2012R0105,Adelaide,2012,R1,2000686938,"Doughty, Michael",208,17,5,4,...,0,8,8,0,0,2,0,0,81,-
3,2012R0105,Adelaide,2012,R1,2006687579,"Douglas, Richard",96,19,14,6,...,0,6,16,0,1,5,0,2,83,-
4,2012R0105,Adelaide,2012,R1,2010728130,"Henderson, Ricky",31,8,5,1,...,0,2,5,0,0,1,0,1,36,Off

In [67]:
stats_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118864 entries, 0 to 118863
Data columns (total 31 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   GameId                  118864 non-null  object
 1   Team                    118864 non-null  object
 2   Year                    118864 non-null  int64
 3   Round                   118864 non-null  object
 4   PlayerId                118864 non-null  int64
 5   DisplayName             118864 non-null  object
 6   GameNumber              118864 non-null  int64
 7   Disposals               118864 non-null  int64
 8   Kicks                   118864 non-null  int64
 9   Marks                   118864 non-null  int64
 10  Handballs               118864 non-null  int64
 11  Goals                   118864 non-null  int64
 12  Behinds                 118864 non-null  int64
 13  HitOuts                 118864 non-null  int64
 14  Tackles                 118864 non-null  int64
 15  Rebounds                118864 non-null  int64
 16  Inside50s               118864 non-null  int64
 17  Clearances              118864 non-null  int64
 18  Clangers                118864 non-null  int64
 19  Frees                   118864 non-null  int64
 20  FreesAgainst            118864 non-null  int64
 21  BrownlowVotes           118864 non-null  int64
 22  ContestedPossessions    118864 non-null  int64
 23  UncontestedPossessions  118864 non-null  int64
 24  ContestedMarks          118864 non-null  int64
 25  MarksInside50           118864 non-null  int64
 26  OnePercenters           118864 non-null  int64
 27  Bounces                 118864 non-null  int64
 28  GoalAssists             118864 non-null  int64
 29  %Played                 118864 non-null  int64
 30  Subs                    75304 non-null   object
dtypes: int64(26), object(5)
memory usage: 28.1+ MB

In [68]:
#Merging stats and player data to get player position
stats_players=stats_data.merge(player_data[["PlayerId","Position"]], on="PlayerId", how="inner")

In [69]:
stats_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118864 entries, 0 to 118863
Data columns (total 32 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   GameId                  118864 non-null  object
 1   Team                    118864 non-null  object
 2   Year                    118864 non-null  int64
 3   Round                   118864 non-null  object
 4   PlayerId                118864 non-null  int64
 5   DisplayName             118864 non-null  object
 6   GameNumber              118864 non-null  int64
 7   Disposals               118864 non-null  int64
 8   Kicks                   118864 non-null  int64
 9   Marks                   118864 non-null  int64
 10  Handballs               118864 non-null  int64
 11  Goals                   118864 non-null  int64
 12  Behinds                 118864 non-null  int64
 13  HitOuts                 118864 non-null  int64
 14  Tackles                 118864 non-null  int64
 15  Rebounds                118864 non-null  int64
 16  Inside50s               118864 non-null  int64
 17  Clearances              118864 non-null  int64
 18  Clangers                118864 non-null  int64
 19  Frees                   118864 non-null  int64
 20  FreesAgainst            118864 non-null  int64
 21  BrownlowVotes           118864 non-null  int64
 22  ContestedPossessions    118864 non-null  int64
 23  UncontestedPossessions  118864 non-null  int64
 24  ContestedMarks          118864 non-null  int64
 25  MarksInside50           118864 non-null  int64
 26  OnePercenters           118864 non-null  int64
 27  Bounces                 118864 non-null  int64
 28  GoalAssists             118864 non-null  int64
 29  %Played                 118864 non-null  int64
 30  Subs                    75304 non-null   object
 31  Position                118864 non-null  object
dtypes: int64(26), object(6)
memory usage: 29.0+ MB

In [70]:
stats_players.head()

,GameId,Team,Year,Round,PlayerId,DisplayName,GameNumber,Disposals,Kicks,Marks,...,ContestedPossessions,UncontestedPossessions,ContestedMarks,MarksInside50,OnePercenters,Bounces,GoalAssists,%Played,Subs,Position
0,2012R0105,Adelaide,2012,R1,2011675768,"Callinan, Ian",4,18,14,5,...,9,9,0,3,0,0,0,84,-,Forward
1,2012R0105,Adelaide,2012,R1,2008681760,"Dangerfield, Patrick",65,25,13,3,...,14,11,0,1,1,1,0,92,-,"Midfield, Forward"
2,2012R0105,Adelaide,2012,R1,2000686938,"Doughty, Michael",208,17,5,4,...,8,8,0,0,2,0,0,81,-,Defender
3,2012R0105,Adelaide,2012,R1,2006687579,"Douglas, Richard",96,19,14,6,...,6,16,0,1,5,0,2,83,-,"Midfield, Forward"
4,2012R0105,Adelaide,2012,R1,2010728130,"Henderson, Ricky",31,8,5,1,...,2,5,0,0,1,0,1,36,Off,Midfield

In [71]:
#choosing numerical stats as features(per game averages):
feature_num=["Disposals", "Kicks", "Marks", "Handballs",
    "Goals", "Behinds", "HitOuts", "Tackles",
    "Rebounds", "Inside50s", "Clearances",
    "ContestedPossessions", "UncontestedPossessions",
    "ContestedMarks", "MarksInside50", "OnePercenters",
    "Bounces", "GoalAssists", "%Played"]

In [72]:
feature_num

['Disposals',
 'Kicks',
 'Marks',
 'Handballs',
 'Goals',
 'Behinds',
 'HitOuts',
 'Tackles',
 'Rebounds',
 'Inside50s',
 'Clearances',
 'ContestedPossessions',
 'UncontestedPossessions',
 'ContestedMarks',
 'MarksInside50',
 'OnePercenters',
 'Bounces',
 'GoalAssists',
 '%Played']

In [73]:
#aggregate per player per game stats
player_features=(
    stats_players.groupby(['PlayerId','Position'])[feature_num].mean().reset_index()
)

In [74]:
player_features.head()

,PlayerId,Position,Disposals,Kicks,Marks,Handballs,Goals,Behinds,HitOuts,Tackles,...,Inside50s,Clearances,ContestedPossessions,UncontestedPossessions,ContestedMarks,MarksInside50,OnePercenters,Bounces,GoalAssists,%Played
0,1993707514,Defender,16.641509,12.698113,5.452830,3.943396,0.056604,0.056604,0.000000,0.962264,...,1.018868,0.169811,4.037736,10.679245,0.320755,0.018868,6.056604,0.037736,0.056604,87.056604
1,1996722607,Forward,23.211009,12.834862,4.146789,10.376147,1.311927,0.706422,0.009174,2.431193,...,3.926606,1.935780,6.550459,16.302752,0.165138,0.559633,0.834862,2.366972,0.779817,87.871560
2,1997774920,Midfield,15.153846,7.692308,2.384615,7.461538,0.307692,0.230769,0.076923,5.153846,...,1.538462,2.692308,6.538462,9.000000,0.000000,0.230769,0.923077,0.000000,0.230769,76.846154
3,1998668708,Midfield,23.307692,9.884615,2.500000,13.423077,0.307692,0.423077,0.000000,3.692308,...,2.615385,4.653846,11.500000,12.538462,0.038462,0.230769,1.115385,0.192308,0.923077,73.538462
4,1998808544,"Midfield, Forward",20.450000,11.350000,4.200000,9.100000,0.000000,0.050000,0.000000,2.600000,...,1.350000,1.750000,7.450000,12.750000,0.250000,0.150000,2.200000,0.100000,0.100000,80.850000

In [75]:
player_features['Position'].value_counts()

Position
Defender              512
Forward               477
Midfield              354
Midfield, Forward     152
Ruck                   85
Defender, Midfield     59
Defender, Forward      44
Forward, Ruck          40
Midfield, Ruck          1
Defender, Ruck          1
Name: count, dtype: int64

In [76]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [77]:
player_features["Position"].value_counts()

Position
Defender              512
Forward               477
Midfield              354
Midfield, Forward     152
Ruck                   85
Defender, Midfield     59
Defender, Forward      44
Forward, Ruck          40
Midfield, Ruck          1
Defender, Ruck          1
Name: count, dtype: int64

In [78]:
def simplify_position(pos):
    if "Defender" in pos:
        return "Defender"
    if "Midfield" in pos:
        return "Midfield"
    if "Forward" in pos:
        return "Forward"
    if "Ruck" in pos:
        return "Ruck"
    return pos

player_features["Position_simple"] = player_features["Position"].apply(simplify_position)

X = player_features[feature_num]
y = player_features["Position_simple"]

In [ ]:
#X=player_features[feature_num]
#y=player_features['Position']
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2, random_state=42)

In [80]:
#scaling features
scaler= StandardScaler()
X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

rf_classifier= RandomForestClassifier(n_estimators=300, random_state=42,class_weight='balanced')
rf_classifier.fit(X_train_scaled, y_train)
y_pred=rf_classifier.predict(X_test_scaled)

In [81]:
print(f"Role Classifier Accuracy:{accuracy_score(y_test, y_pred)}")
print(f"Classication Report:{classification_report(y_test, y_pred)}")
print(f"Confusion Matrix:\n{confusion_matrix(y_test, y_pred)}")

Role Classifier Accuracy:0.7420289855072464
Classication Report:              precision    recall  f1-score   support

    Defender       0.79      0.78      0.78       120
     Forward       0.73      0.73      0.73       106
    Midfield       0.70      0.73      0.71        97
        Ruck       0.79      0.68      0.73        22

    accuracy                           0.74       345
   macro avg       0.75      0.73      0.74       345
weighted avg       0.74      0.74      0.74       345

Confusion Matrix:
[[93 10 16  1]
 [11 77 15  3]
 [14 12 71  0]
 [ 0  7  0 15]]